# Generated by Django 4.1.3 on 2022-12-20 10:40

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('secretsmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='secret',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
        migrations.AlterField(
            model_name='secret',
            name='title',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
    ]
